name: Pylint

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock pytest-split pytest-cov mypy pydocstyle pylint black flake8 pyproject-flake8==6.0.0
        pip install types-setuptools
        pip install .
    - name: mypy
      run: |
        mypy --version
        rm -rf .mypy_cache
        mypy autoplex
    - name: pydocstyle
      run: |
        pydocstyle --config pyproject.toml --count autoplex
    - name: pylint
      run: |
        pylint --version
        pylint --rcfile=pylintrc autoplex
    - name: black
      run: |
        black --version
        black --check --diff --color autoplex
    - name: pflake8
      run: |
        pflake8 --version
        pflake8 --count --show-source --statistics autoplex
        pflake8 --count --exit-zero --max-complexity=20 --statistics autoplex
