# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Testing Linux

on:
  push:
    branches: ['*']
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        split: [1] #[1, 2, 3, 4]  # Number of splits

    steps:
    - uses: actions/checkout@v3
    - name: Check Docker availability
      run: docker --version
    - name: Pull and Set up Docker image for Python ${{ matrix.python-version }}
      run: |
        docker pull ghcr.io/jageo/autoplex/autoplex:python-${{ matrix.python-version }}
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          ghcr.io/jageo/autoplex/autoplex:python-${{ matrix.python-version }} \
          bash -c "
          python -m pip install --upgrade pip && \
          python -m uv pip install pytest pytest-mock pytest-split pytest-cov types-setuptools && \
          python -m uv pip install .[strict] && \
          python -m uv pip install ase==3.23.0 && \
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics && \
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics && \
          pytest --cov=autoplex --cov-report term-missing --cov-append --splits 1 --group ${{ matrix.split }} -vv --durations-path ./tests/test_data/.pytest-split-durations
        "
    - name: Upload coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage-${{ matrix.split }}
        path: .coverage
        
  coverage:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - name: Install Coverage
          run: |
           python -m pip install coverage[toml]
        - name: Download coverage artifacts
          continue-on-error: true
          uses: actions/download-artifact@v3
        - name: Run coverage
          continue-on-error: true
          run: |
            coverage combine coverage*/.coverage*
            coverage report --show-missing

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs,strict]

      - name: Build
        run: sphinx-build -W docs _build
